GET http://localhost:8283/
Content-Type: application/json
{
  "actions": [
    {
      "type": "Download",
      "name": "download",
      "data": {
        "url": "https://habrahabr.ru/"
      },
      "settings": {
        "visible": false,
        "filters":  {
          "WhitelistUrlFilter": {
            "urls": [".*habrahabr\\.ru.*"]
          }
        }
      }
    },
    {
      "type": "Paginate",
      "name": "pages",
      "target": "download",
      "data": {
        "selector": "#nav-pages li a"
      },
      "settings": {
        "visible": false
      }
    },
    {
      "type": "Parse",
      "name": "header",
      "target": "pages",
      "data": {
        "selector": ".post__title_link[outerHTML]"
      },
      "settings": {
        "visible": false
      }
    },
    {
      "type": "Parse",
      "name": "caption",
      "target": "header",
      "data": {
        "selector": "[text]"
      },
      "settings": {
        "visible": true
      }
    },
    {
      "type": "Parse",
      "name": "link",
      "target": "header",
      "data": {
        "selector": "[href]"
      },
      "settings": {
        "visible": true
      }
    }
  ]
}
